### ISSUE TITLE
no such file or directory, open '/Users/ifable/Desktop/explore/kue/node_modules/kue-ui-express/node_modules/kue-ui-client/dist/index.html'

### ISSUE THREAD

**Issue by changjunhao** [stonecircle/kue-ui-express#1]
Error: ENOENT: no such file or directory, open '/Users/ifable/Desktop/explore/kue/node_modules/kue-ui-express/node_modules/kue-ui-client/dist/index.html'
    at Object.fs.openSync (fs.js:582:18)
    at Object.fs.readFileSync (fs.js:489:33)
    at Object.<anonymous> (/Users/ifable/Desktop/explore/kue/node_modules/kue-ui-express/lib/mountKueUi.js:6:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by mansona** [comment]
@changjunhao thanks for the report, I could see **exactly** what the issue was thanks to your stack trace 👍 

I have just released kue-ui-express@1.0.1 which should fix this issue for you, I've just tested it in a non test environment so I'm confident that it has been fixed. 

Please re-open this issue if you have any problems
